version: '3.2'

services:

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: thieunm
      MYSQL_PASSWORD: nmtkma0550
      MYSQL_DATABASE: messaging
      MYSQL_ROOT_PASSWORD: nmtkma0550
    healthcheck:
      test: "exit 0"